parameters:
    database_driver: pdo_mysql
    database_host: localhost
    database_port: null
    database_name: SonataSammie
    database_user: root
    database_password: null
    mailer_transport: smtp
    mailer_host: localhost
    mailer_user: null
    mailer_password: null
    locale: en
    secret: '123j123l1k2j3l12k3j12lk3 l'
    database_path: null
